// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
// ...
await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiBDq19Is5aF9B274aJt-52hdzo3mi2cE',
    appId: '1:603607348131:web:fe69e76947710f930b2016',
    messagingSenderId: '603607348131',
    projectId: 'soa-starter-d9688',
    authDomain: 'soa-starter-d9688.firebaseapp.com',
    storageBucket: 'soa-starter-d9688.firebasestorage.app',
    measurementId: 'G-QGVF2XQ847',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtG7cx11DZYxGRnQ5H81G03eG2rPbaiOo',
    appId: '1:603607348131:android:947d57547b03bbb10b2016',
    messagingSenderId: '603607348131',
    projectId: 'soa-starter-d9688',
    storageBucket: 'soa-starter-d9688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJKjckItAYVbjxfJAq3f0P9UHWYIZ4w7k',
    appId: '1:603607348131:ios:38043eda3bcdb72d0b2016',
    messagingSenderId: '603607348131',
    projectId: 'soa-starter-d9688',
    storageBucket: 'soa-starter-d9688.firebasestorage.app',
    iosBundleId: 'com.example.soaStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJKjckItAYVbjxfJAq3f0P9UHWYIZ4w7k',
    appId: '1:603607348131:ios:38043eda3bcdb72d0b2016',
    messagingSenderId: '603607348131',
    projectId: 'soa-starter-d9688',
    storageBucket: 'soa-starter-d9688.firebasestorage.app',
    iosBundleId: 'com.example.soaStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiBDq19Is5aF9B274aJt-52hdzo3mi2cE',
    appId: '1:603607348131:web:0b6735cc174240460b2016',
    messagingSenderId: '603607348131',
    projectId: 'soa-starter-d9688',
    authDomain: 'soa-starter-d9688.firebaseapp.com',
    storageBucket: 'soa-starter-d9688.firebasestorage.app',
    measurementId: 'G-CT6EWR5BX2',
  );
}
